"""Add UniqueConstraint and Indexes

Revision ID: 3df6987d399b
Revises: f5788ae05733
Create Date: 2026-05-30 15:51:25.451330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df6987d399b'
down_revision: Union[str, None] = 'f5788ae05733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_result_run_strategy', 'backtest_results', ['run_id', 'strategy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_unique_constraint('uq_result_run_strategy', 'backtest_results')
    # ### end Alembic commands ###
