"""add_sweep_analysis_fields

Revision ID: acae46605fc7
Revises: c20a6f891d6e
Create Date: 2026-06-09 22:39:22.600549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acae46605fc7'
down_revision: Union[str, None] = 'c20a6f891d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('management_family', sa.TEXT(), nullable=True))
    op.add_column('backtest_results', sa.Column('regime_type', sa.TEXT(), nullable=True))
    op.add_column('backtest_results', sa.Column('session', sa.TEXT(), nullable=True))
    op.add_column('backtest_results', sa.Column('news_state', sa.TEXT(), nullable=True))
    op.add_column('backtest_results', sa.Column('exit_efficiency', sa.NUMERIC(precision=18, scale=4), nullable=True))
    op.add_column('backtest_results', sa.Column('theoretical_fixed_tp_net_pnl', sa.NUMERIC(precision=18, scale=4), nullable=True))
    op.add_column('backtest_results', sa.Column('theoretical_fixed_tp_win', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('backtest_results', sa.Column('opportunity_cost_flag', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('backtest_results', sa.Column('lot_floor_violation', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('backtest_results', sa.Column('risk_exceeded_due_to_min_lot', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('backtest_runs', sa.Column('sweep_id', sa.TEXT(), nullable=True))
    op.add_column('backtest_runs', sa.Column('sweep_name', sa.TEXT(), nullable=True))
    op.add_column('backtest_runs', sa.Column('management_family', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_runs', 'management_family')
    op.drop_column('backtest_runs', 'sweep_name')
    op.drop_column('backtest_runs', 'sweep_id')
    op.drop_column('backtest_results', 'risk_exceeded_due_to_min_lot')
    op.drop_column('backtest_results', 'lot_floor_violation')
    op.drop_column('backtest_results', 'opportunity_cost_flag')
    op.drop_column('backtest_results', 'theoretical_fixed_tp_win')
    op.drop_column('backtest_results', 'theoretical_fixed_tp_net_pnl')
    op.drop_column('backtest_results', 'exit_efficiency')
    op.drop_column('backtest_results', 'news_state')
    op.drop_column('backtest_results', 'session')
    op.drop_column('backtest_results', 'regime_type')
    op.drop_column('backtest_results', 'management_family')
    # ### end Alembic commands ###
