"""Add mae_pips and mfe_pips

Revision ID: c20a6f891d6e
Revises: 3df6987d399b
Create Date: 2026-06-09 05:12:23.280056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20a6f891d6e'
down_revision: Union[str, None] = '3df6987d399b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('mae_pips', sa.NUMERIC(precision=18, scale=4), nullable=True))
    op.add_column('backtest_results', sa.Column('mfe_pips', sa.NUMERIC(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_results', 'mfe_pips')
    op.drop_column('backtest_results', 'mae_pips')
    # ### end Alembic commands ###
