"""Initial backtest schema

Revision ID: f5788ae05733
Revises: 
Create Date: 2026-05-30 21:07:13.010011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f5788ae05733'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('run_name', sa.TEXT(), nullable=True),
    sa.Column('profile_name', sa.TEXT(), nullable=False),
    sa.Column('profile_version', sa.TEXT(), nullable=False),
    sa.Column('engine_version', sa.TEXT(), nullable=False),
    sa.Column('source_database_name', sa.TEXT(), nullable=False),
    sa.Column('source_database_fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategy_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ea_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ea_config_hash', sa.TEXT(), nullable=False),
    sa.Column('broker_specs_hash', sa.TEXT(), nullable=False),
    sa.Column('trade_executor_hash', sa.TEXT(), nullable=False),
    sa.Column('fill_model', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('total_strategies', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('processed_strategies', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('executed_trades', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('no_trade_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unsupported_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('backtest_artifacts',
    sa.Column('artifact_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.TEXT(), nullable=False),
    sa.Column('path', sa.TEXT(), nullable=False),
    sa.Column('sha256', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_table('backtest_results',
    sa.Column('result_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('strategy_hash', sa.TEXT(), nullable=False),
    sa.Column('profile_hash', sa.TEXT(), nullable=False),
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('direction', sa.TEXT(), nullable=False),
    sa.Column('condition_type', sa.TEXT(), nullable=True),
    sa.Column('timeframe', sa.TEXT(), nullable=True),
    sa.Column('confirmation', sa.TEXT(), nullable=True),
    sa.Column('strategy_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('strategy_expiry_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('outcome', sa.TEXT(), nullable=False),
    sa.Column('outcome_reason', sa.TEXT(), nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('entry_price', sa.NUMERIC(precision=18, scale=8), nullable=True),
    sa.Column('exit_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('exit_price', sa.NUMERIC(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.NUMERIC(precision=18, scale=8), nullable=True),
    sa.Column('stop_loss', sa.NUMERIC(precision=18, scale=8), nullable=True),
    sa.Column('initial_stop_loss', sa.NUMERIC(precision=18, scale=8), nullable=True),
    sa.Column('final_stop_loss', sa.NUMERIC(precision=18, scale=8), nullable=True),
    sa.Column('lot_size', sa.NUMERIC(precision=12, scale=4), nullable=True),
    sa.Column('partial_close_executed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('break_even_moved', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('hit_tp', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('hit_sl', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('gross_pnl', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('commission', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('swap', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('net_pnl', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('pnl_pips', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('r_multiple', sa.NUMERIC(precision=18, scale=6), nullable=True),
    sa.Column('balance_before', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('balance_after', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('equity_high_watermark', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('drawdown_after', sa.NUMERIC(precision=18, scale=6), nullable=True),
    sa.Column('bars_scanned', sa.Integer(), nullable=True),
    sa.Column('debug', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_backtest_results_run_id'), 'backtest_results', ['run_id'], unique=False)
    op.create_index('ix_backtest_results_strategy', 'backtest_results', ['strategy_id', 'strategy_hash', 'profile_hash'], unique=False)
    op.create_index('ix_backtest_results_symbol_outcome', 'backtest_results', ['symbol', 'outcome'], unique=False)
    op.create_index('ix_backtest_results_condition_outcome', 'backtest_results', ['condition_type', 'outcome'], unique=False)
    op.create_index('ix_backtest_results_entry_time', 'backtest_results', ['entry_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtest_results_entry_time', table_name='backtest_results')
    op.drop_index('ix_backtest_results_condition_outcome', table_name='backtest_results')
    op.drop_index('ix_backtest_results_symbol_outcome', table_name='backtest_results')
    op.drop_index('ix_backtest_results_strategy', table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_run_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_table('backtest_artifacts')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
